In [ ]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
from google.colab import drive
drive.mount('/content/drive')
drive_path = '/content/drive/MyDrive/PFA' 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import cv2
import csv
from glob import glob
from tqdm import tqdm
import numpy as np
import imutils

pathcsv = os.path.join("/content/drive/MyDrive/PFA/new_data/real_size.csv")


In [ ]:
def load_data(path):
    
    predicted_masks = sorted(glob(f"{path}/single_resnet50/*.bmp"))
    predicted_roi = sorted(glob(f"{path}/single_roi_dense/*.bmp"))
    print(len(predicted_masks))
   
    return predicted_masks, predicted_roi

In [ ]:
def find_size(elem):
  original_height = 0
  original_width = 0
  filecsv = open(pathcsv)
  real_sizes = csv.reader(filecsv)
  for row in real_sizes:
    if row[0]==elem :
      original_height= int(row[1])
      original_width= int(row[2])

  return original_width, original_height

In [ ]:
def area(image, area_type=None):
  #this part just shows the nb of pixels with a specific colour
  colours, counts = np.unique(image.reshape(-1,1), axis=0, return_counts=1)
  if area_type == 'full':
    print(colours,counts)
    return counts[1]
  else :
    area_zp = counts[1]
    area_te = counts[2]
    area_icm = counts[3]
    return area_zp, area_te, area_icm

In [ ]:
from google.colab.patches import cv2_imshow


In [ ]:
def zp_thickness(image, roi):
  roi=roi.copy()
  roi = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
  thresh = cv2.threshold(roi, 60, 255, cv2.THRESH_BINARY)[1]
  cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
  cnts = imutils.grab_contours(cnts)

  # loop over the contours
  for c in cnts:
    # compute the center of the contour
    M = cv2.moments(c)
    cX = int(M["m10"] / M["m00"])
    cY = int(M["m01"] / M["m00"])


  w = image.shape[0]
  h = image.shape[1]
  h_c=cX
  w_c=cY  
  width=0
  zp_right=0
  while(width<=w_c) :
    print(image[h_c,width])
    print(image[h_c,width].shape)
    if image[h_c,width]==63 :
        zp_right=zp_right+1
    width=width+1

  width=w_c
  zp_left=0
  while(width<w) :
      if image[h_c,width]==63 :
          zp_left=zp_left+1
      width=width+1

  height=0
  zp_high=0
  while (height<=h_c) :
        if image[height,w_c]==63 :
          zp_high=zp_high+1
        height=height+1

  height=h_c
  zp_down=0
  while (height<h) :
        if image[height,w_c]==63 :
          zp_down=zp_down+1
        height=height+1

  zp_thickness=(zp_down+zp_high+zp_right+zp_left)/4
  
  
  return zp_thickness

In [ ]:
import math


In [ ]:
def extract(predicted_masks, predicted_rois):
    """Performing data augmentation"""
   
    print(len(predicted_masks))
    for idx, (i, roi) in tqdm(enumerate(zip(predicted_masks, predicted_rois)), total=len(predicted_masks)):
        
        name_mask = i.split("/")[-1].split(".")[0]
        
        name_mask=name_mask.replace(' ROI', '')
        
        name_mask += '.bmp'
        predicted_mask = cv2.imread(i)
        predicted_roi = cv2.imread(roi)
        width, height = find_size(name_mask)
        
        print(name_mask)
        mask = cv2.resize(predicted_mask, (width, height), interpolation = cv2.INTER_NEAREST)
        full = cv2.resize(predicted_roi, (width, height), interpolation = cv2.INTER_NEAREST)
        area_zp, area_te, area_icm = area(mask)
        full_area = area(full,'full')
        radius = math.sqrt(full_area / math.pi)
        print(radius)
        thickness = zp_thickness(mask, full)  
        print(thickness)

In [ ]:
predicted_masks, predicted_roi = load_data(drive_path)
extract(predicted_masks, predicted_roi)

48
48


  0%|          | 0/48 [00:00<?, ?it/s]

Streaming output truncated to the last 5000 lines.
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
(3,)
[0 0 0]
